### ISSUE TITLE
Split styles & editingConfig into separate files

### ISSUE THREAD

**Issue by thomasritz** [Scrivito/scrivito-neoletter-form-widgets#13]
For the  Portal app  we need to provide 2 imports of 2 different files in order to reduce the size when editingMode is not active, i.e. have an index.js to import only component & class and another one to import the editingConfig only.
For the styles, we also need to create separate files, one for the stylings in the form itself and one for the component styles which are used in the properties.

- [x] separate styles
- [x] separate editingConfig

**Comment by thomasritz** [comment]
https://github.com/Scrivito/scrivito-portal-app/pull/365

**Comment by aea-JR** [comment]
Additionally removed lodash-es dependency and created some own lodash polyfills.
Removed react-bootstrap dependency and created self made modal and popover components.
Removed both friendly-challenge & google-recaptcha dependencies and refactored the components to work worhout them.
Updated tests & readme.
New package released.
waiting for merge.
